<?php

/**
 * User edit Lister
 * Give edit permissions for user template for users that have user-admin
 *
 */
class UserEditLister extends WireData implements Module {
    public static function getModuleInfo() {
        return array(
            'title' => 'User edit Lister',
            'summary' => __('Allow to edit users inside lister when users have the user-admin permission.'),
            'version' => '0.0.1',
            'author' => 'Martijn Geerts (Calago)',
            'icon' => 'user',
            'autoload' => function() {
                // Superusers get access any way, return false
                if (wire('user')->isSuperuser()) return false;
                // Autoload when user has permission to edit users
                return wire('user')->hasPermission('user-admin');
            },
        );
    }

    public function init() {
        $this->addHookAfter('Page::editable', function($event) {
            if ($event->object->template != 'user') return;
            $event->return = true;
        });
    }
}
